baseurl = "/"
languageCode = "en-us"
title = "Eliezer Encarnacion - My Personal site"
theme = "xmin"
googleAnalytics = "UA-112742588-1"
disqusShortname = "eliezerencarnacion"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[params]
    description = "A personal website powered by hugo"
    footer = "&copy; Eliezer Encarnacion 2018 | Powered by [Hugo] (https://gohugo.io/) and the [XMin theme](https://github.com/yihui/hugo-xmin)"
    github="eliezer15"
    email="eliezerencarncion@gmail.com"
    linkedin="eliezer-encarnacion-bbab995a"
    stackoverflow="8665434"